# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

# Rust toolchain specification
# See https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
# Using nightly to support unstable rustfmt features in rustfmt.toml

[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc"]
profile = "default"
